# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='html_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='HTML title'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=255, verbose_name='tytuł (alt)'),
        ),
    ]
